export const deleteModel =
  "\
    DROP TABLE DETALLE_CONTACTO; \
    DROP TABLE DETALLE_UBICACION; \
    DROP TABLE UBICACION; \
    DROP TABLE DETALLE_ASOCIADO; \
    DROP TABLE ASOCIADOS; \
    DROP TABLE CASO; \
    DROP TABLE DETALLE_TRATAMIENTO; \
    DROP TABLE TRATAMIENTO; \
    DROP TABLE VICTIMAS; \
    DROP TABLE HOSPITALES; \
";
